<?php 
$last_segment = $block->getCurrentUrl();
$categoryId = $block->getCategoryByUrlKey($last_segment);
$addClass = '';
$product = []; 
$getCategoryHtmlContentForCateSlider = false;
if ($categoryId) {
    // print_r($categoryId->getData());die;
    $subCategories = $block->getSubcategoriesByParentId($categoryId->getEntityId()); 
    $getCategoryHtmlContentForCateSlider = ($categoryId->getCategoryHtmlContentForCateSlider()) ? $categoryId->getCategoryHtmlContentForCateSlider() : false;
    if (!(count($subCategories) > 0)) {
        $addClass = 'hide-content';
    }
?>
<section class="sub-category-section py-50 <?=$addClass?>">
    <div class="container mb-4">
        <div class="row d-flex align-items-center mb-4">
            <?php if ($getCategoryHtmlContentForCateSlider) { ?>
                <div class="col-lg-6 col-md-9">
                    <?php echo $getCategoryHtmlContentForCateSlider; ?>
                </div>
            <?php } ?>
            <div class="col-lg-6 col-md-3 text-md-end text-start">
                <a href="#" class="btn purple-outline">Take Quiz</a>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="sub-category-slider">
                <?php foreach($subCategories as $subCategory) { ?>
                    <div class="slider-item px-2">
                        <div class="slider-inner">
                            <div class="d-block mb-3">
                                <a href="#"><img src="<?php echo $subCategory->getImageUrl(); ?>" alt="" /></a>
                            </div>
                            <div class="d-flex justify-content-between">
                                <h5><?php echo $subCategory->getName(); ?></h5>
                            </div>
                        </div>
                    </div>
                <?php } ?>
                </div>
            </div>
        </div>
    </div>
</section>
<style>
    .category-product-slider-sec.hide-content{
        display: none;
    }
</style>
<script>
    require(['jquery', 'slick'], function($) {
        $(document).ready(function(){
            $('.sub-category-slider').slick({
                slidesToShow: 4, 
                slidesToScroll: 1,
                autoplay: true,
                autoplaySpeed: 2000,
                arrows: false,
                dots: false,
                responsive: [
                    {
                        breakpoint: 1024,
                        settings: {
                        slidesToShow: 2
                        }
                    },
                    {
                        breakpoint: 768,
                        settings: {
                        slidesToShow: 2
                        }
                    },
                    {
                        breakpoint: 640,
                        settings: {
                        slidesToShow: 1
                        }
                    }
                ]
            });
        });
    });
</script>
<?php } ?>