<?php 
$last_segment = $block->getCurrentUrl();
$categoryId = $block->getCategoryByUrlKey($last_segment);
$addClass = '';
$product = []; // Initialize $product as an empty array
// $showCategoryContent = false; // Initialize flag to show/hide category content
if ($categoryId) {
    $product = $block->getProductCollectionByCategoryId($categoryId->getEntityId()); 
    if (!(count($product) > 0)) {
        // $showCategoryContent = true; // Set flag to true if there are products
        $addClass = 'hide-content';
    }
}
?>
<section class="category-product-slider-sec py-50 <?=$addClass?>">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 mb-4">
            <?php echo $categoryId->getCategoryHtmlContent(); ?>
            </div>
            <div class="col-lg-12">
                <div class="category-product-slider">
                <?php foreach($product as $productData) { ?>
                    <div class="slider-item px-2">
                        <div class="slider-inner">
                            <div class="d-block mb-3">
                                <a href="#"><img src="<?php echo '/media/catalog/product'. $productData->getimage(); ?>" /></a>
                            </div>
                            <div class="d-flex justify-content-between">
                                <div class="d-block">
                                    <h5 class="pr-name"><?php echo $productData->getName(); ?></h5>
                                    <p class="pr-tag">Safety info</p>
                                </div>
                                <div class="d-block">
                                    <a href="#" class="btn green-btn">Get Started</a>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php } ?>
                </div>
            </div>
        </div>
    </div>
</section>
<style>
    .category-product-slider-sec.hide-content{
        display: none;
    }
</style>
<script>
    require(['jquery', 'slick'], function($) {
        $(document).ready(function(){
            $('.category-product-slider').slick({
                slidesToShow: 4, 
                slidesToScroll: 1,
                autoplay: true,
                autoplaySpeed: 3000,
                arrows: true,
                dots: false,
                prevArrow:'<button type="button" data-role="none" class="slick-prev"></button>',
                nextArrow:'<button type="button" data-role="none" class="slick-next"></button>',
                responsive: [
                    {
                        breakpoint: 1024,
                        settings: {
                        slidesToShow: 2
                        }
                    },
                    {
                        breakpoint: 768,
                        settings: {
                        slidesToShow: 2
                        }
                    },
                    {
                        breakpoint: 640,
                        settings: {
                        slidesToShow: 1
                        }
                    }
                ]
            });
        });
    });
</script>