<?php $product = $block->getProductCollection(); ?>
<?php 
    // foreach($product as $productData){
    //     print_r($productData->getData()); die;
    // }
?>
<section class="product-slider-block py-50">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 mb-4 text-center">
                <h2 class="sec-title">Amazing Product Are Ready For You <span>Ready For You</span></h2>
            </div>
            <div class="col-lg-12">
                <div class="product-slider">
                <?php foreach($product as $productData) { ?>
                    <div class="slider-item px-2">
                        <div class="slider-inner">
                            <div class="d-block mb-3">
                                <a href="#"><img src="<?php echo '/media/catalog/product'. $productData->getimage(); ?>" /></a>
                            </div>
                            <div class="d-flex justify-content-between">
                                <div class="d-block">
                                    <h5 class="pr-name"><?php echo $productData->getName(); ?></h5>
                                    <p class="pr-tag">Safety info</p>
                                </div>
                                <div class="d-block">
                                    <a href="#" class="btn green-btn">Get Started</a>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php } ?>
                    <!-- <div class="slider-item px-2">
                        <div class="slider-inner">
                            <div class="d-block mb-3">
                                <a href="#"><img src="<?php echo '/media/wysiwyg/Rectangle_19_1_.png' ?>" /></a>
                            </div>
                            <div class="d-flex justify-content-between">
                                <div class="d-block">
                                    <h5 class="pr-name">Hard Mints</h5>
                                    <p class="pr-tag">Safety info</p>
                                </div>
                                <div class="d-block">
                                    <a href="#" class="btn green-btn">Get Started</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="slider-item px-2">
                        <div class="slider-inner">
                            <div class="d-block mb-3">
                                <a href="#"><img src="<?php echo '/media/wysiwyg/Rectangle_19_2_.png' ?>" /></a>
                            </div>
                            <div class="d-flex justify-content-between">
                                <div class="d-block">
                                    <h5 class="pr-name">Hard Mints</h5>
                                    <p class="pr-tag">Safety info</p>
                                </div>
                                <div class="d-block">
                                    <a href="#" class="btn green-btn">Get Started</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="slider-item px-2">
                        <div class="slider-inner">
                            <div class="d-block mb-3">
                                <a href="#"><img src="<?php echo '/media/wysiwyg/Rectangle_19.png' ?>" /></a>
                            </div>
                            <div class="d-flex justify-content-between">
                                <div class="d-block">
                                    <h5 class="pr-name">Hard Mints</h5>
                                    <p class="pr-tag">Safety info</p>
                                </div>
                                <div class="d-block">
                                    <a href="#" class="btn green-btn">Get Started</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="slider-item px-2">
                        <div class="slider-inner">
                            <div class="d-block mb-3">
                                <a href="#"><img src="<?php echo '/media/wysiwyg/Rectangle_19_1_.png' ?>" /></a>
                            </div>
                            <div class="d-flex justify-content-between">
                                <div class="d-block">
                                    <h5 class="pr-name">Hard Mints</h5>
                                    <p class="pr-tag">Safety info</p>
                                </div>
                                <div class="d-block">
                                    <a href="#" class="btn green-btn">Get Started</a>
                                </div>
                            </div>
                        </div>
                    </div> -->
                </div>
            </div>
        </div>
    </div>
</section>

<script>
    require(['jquery', 'slick'], function($) {
        $(document).ready(function(){
            $('.product-slider').slick({
                slidesToShow: 4, 
                slidesToScroll: 1,
                autoplay: true,
                autoplaySpeed: 3000,
                arrows: true,
                dots: false,
                prevArrow:'<button type="button" data-role="none" class="slick-prev"></button>',
                nextArrow:'<button type="button" data-role="none" class="slick-next"></button>',
                responsive: [
                    {
                        breakpoint: 1024,
                        settings: {
                        slidesToShow: 2
                        }
                    },
                    {
                        breakpoint: 768,
                        settings: {
                        slidesToShow: 2
                        }
                    },
                    {
                        breakpoint: 640,
                        settings: {
                        slidesToShow: 1
                        }
                    }
                ]
            });
        });
    });
</script>