<?php
    $_helper = $this->helper('Smartwave\Porto\Helper\Data');
    $header_type = $this->getConfig('porto_settings/header/header_type');
    $header2_text = $this->getConfig('porto_settings/header/header2_text');
    $show_notice = $this->getConfig('porto_settings/general/show_site_notice');
    if ($show_notice && $show_notice == 1)
        echo $this->getChildHtml("porto_custom_notice");
?>
<?php if($header_type == 10): ?>
<div class="position-relative">
<?php endif;?>
<header class="page-header type<?php echo $header_type; ?>" >
<?php echo $this->getChildHtml("header_customer_form_login"); ?>
<?php if($header_type == 1): ?>
  <!-- <div class="main-panel-top">
      <div class="container">
          <div class="main-panel-inner">
              <div class="panel wrapper">
                <div class="header-left">
                  <div class="panel header">
                      <?php //echo $this->getChildHtml("currency"); ?>
                      <?php //echo $this->getChildHtml("store_language"); ?>
                  </div>
                </div>
                <div class="header-right">
                  <div class="panel header show-icon-tablet">
                    <div class="top-links-icon">
                      <a href="javascript:;"><?php //echo __('Links');?></a>
                    </div>
                    <?php //echo $this->getChildHtml("header.links"); ?>
                  </div>
                  <?php //echo $this->getChildHtml("custom_block_top"); ?>
                </div>
              </div>
          </div>
      </div>
  </div> -->
  <div class="header-main">
    <div class="container">
      <div class="header content header-row">
        <div class="header-left">
          <span data-action="toggle-nav" class="action nav-toggle"><span><?php echo __('Toggle Nav') ?></span></span>
        </div>
        <div class="header-center">
          <?php echo $this->getChildHtml("logo"); ?>
          <!-- <div class="search-area show-icon-tablet">
            <a href="javascript:void(0);" class="search-toggle-icon"><span><i class="porto-icon-magnifier"></i></span></a>
            <?php echo $this->getChildHtml("top.search"); ?>
          </div> -->
        </div>
        <div class="header-right">
          <?php echo $this->getChildHtml("minicart"); ?>
          <div class="header-contact">
            <?php echo $this->getChildHtml("custom_block"); ?>
            <a href="<?php echo $_helper->getBaseLinkUrl(). 'customer/account/' ?>" class="my-account m-l-xs mr-1 mr-lg-2" title="My Account"><i class="porto-icon-user-2"></i></a>
            <!-- <a href="<?php echo $_helper->getBaseLinkUrl(). 'wishlist' ?>" class="wishlist mr-1 mr-lg-2 pr-lg-1" title="Wishlist"><i class="porto-icon-wishlist-2"></i></a> -->
          </div>
        </div>
      </div>
    </div>
  </div>
  <?php echo $this->getChildHtml("navigation.sections"); ?>
<?php else: ?>
  <div class="main-panel-top">
      <div class="container">
          <div class="main-panel-inner">
              <div class="panel wrapper">
                <div class="header-left">
                  <div class="panel header">
                      <?php echo $this->getChildHtml("currency"); ?>
                      <?php echo $this->getChildHtml("store_language"); ?>
                  </div>
                </div>
                <div class="header-right">
                  <div class="panel header show-icon-tablet">
                    <div class="top-links-icon">
                      <a href="javascript:;"><?php echo __('Links');?></a>
                    </div>
                    <?php echo $this->getChildHtml("header.links"); ?>
                  </div>
                  <?php echo $this->getChildHtml("custom_block_top"); ?>
                </div>
              </div>
          </div>
      </div>
  </div>
  <div class="header-main">
    <div class="header content header-row">
      <div class="header-left">
        <span data-action="toggle-nav" class="action nav-toggle"><span><?php echo __('Toggle Nav') ?></span></span>
        <?php echo $this->getChildHtml("logo"); ?>
      </div>
      <div class="header-center">
        <div class="search-area show-icon-tablet">
          <a href="javascript:void(0);" class="search-toggle-icon"><span><i class="porto-icon-magnifier"></i></span></a>
          <?php echo $this->getChildHtml("top.search"); ?>
        </div>
      </div>
      <div class="header-right">
      <?php echo $this->getChildHtml("minicart"); ?>
        <div class="header-contact">
          <?php echo $this->getChildHtml("custom_block"); ?>
          <a href="<?php echo $_helper->getBaseLinkUrl(). 'customer/account/' ?>" class="my-account m-l-xs mr-1 mr-lg-2" title="My Account"><i class="porto-icon-user-2"></i></a>
          <a href="<?php echo $_helper->getBaseLinkUrl(). 'wishlist' ?>" class="wishlist mr-1 mr-lg-2 pr-lg-1" title="Wishlist"><i class="porto-icon-wishlist-2"></i></a>
        </div>
      </div>
    </div>
  </div>
<?php endif; ?>
</header>
<?php if($header_type == 10): ?>
</div>
<?php endif; ?>
<?php
    if ($show_notice && $show_notice == 2)
        echo $this->getChildHtml("porto_custom_notice");
?>


<script type="text/javascript">
  require([
        'jquery'
    ], function ($) {
    $(document).ready(function($) {
        $('[data-action="close-nav"]').on('click', function() {
            $('html').removeClass('nav-open');
        });
    });
  });
</script>