<?php
    $_helper = $this->helper('Smartwave\Porto\Helper\Data');
    $header_type = $this->getConfig('porto_settings/header/header_type');
    $header2_text = $this->getConfig('porto_settings/header/header2_text');
    $show_notice = $this->getConfig('porto_settings/general/show_site_notice');
    if ($show_notice && $show_notice == 1)
        echo $this->getChildHtml("porto_custom_notice");
?>
<?php if($header_type == 10): ?>
<div class="position-relative">
<?php endif;?>
<header class="page-header type<?php echo $header_type; ?>" >
<?php echo $this->getChildHtml("header_customer_form_login"); ?>
<?php if($header_type == 1): ?>
  <!-- <div class="main-panel-top">
      <div class="container">
          <div class="main-panel-inner">
              <div class="panel wrapper">
                <div class="header-left">
                  <div class="panel header">
                      <?php //echo $this->getChildHtml("currency"); ?>
                      <?php //echo $this->getChildHtml("store_language"); ?>
                  </div>
                </div>
                <div class="header-right">
                  <div class="panel header show-icon-tablet">
                    <div class="top-links-icon">
                      <a href="javascript:;"><?php //echo __('Links');?></a>
                    </div>
                    <?php //echo $this->getChildHtml("header.links"); ?>
                  </div>
                  <?php //echo $this->getChildHtml("custom_block_top"); ?>
                </div>
              </div>
          </div>
      </div>
  </div> -->
  <div class="header-main">
    <div class="container">
      <div class="header content header-row">
        <div class="header-left">
          <span data-action="toggle-nav" class="action nav-toggle"><span><?php echo __('Toggle Nav') ?></span></span>
        </div>
        <div class="header-center">
          <?php echo $this->getChildHtml("logo"); ?>
          <!-- <div class="search-area show-icon-tablet">
            <a href="javascript:void(0);" class="search-toggle-icon"><span><i class="porto-icon-magnifier"></i></span></a>
            <?php echo $this->getChildHtml("top.search"); ?>
          </div> -->
        </div>
        <div class="header-right">
          <?php echo $this->getChildHtml("minicart"); ?>
          <div class="header-contact">
            <?php echo $this->getChildHtml("custom_block"); ?>
            <a id="profile-dropdown-toggle" class="my-account m-l-xs mr-1 mr-lg-2">
              <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path d="M12 12.75C8.83 12.75 6.25 10.17 6.25 7C6.25 3.83 8.83 1.25 12 1.25C15.17 1.25 17.75 3.83 17.75 7C17.75 10.17 15.17 12.75 12 12.75ZM12 2.75C9.66 2.75 7.75 4.66 7.75 7C7.75 9.34 9.66 11.25 12 11.25C14.34 11.25 16.25 9.34 16.25 7C16.25 4.66 14.34 2.75 12 2.75Z" fill="black"/>
              <path d="M20.5901 22.75C20.1801 22.75 19.8401 22.41 19.8401 22C19.8401 18.55 16.3202 15.75 12.0002 15.75C7.68015 15.75 4.16016 18.55 4.16016 22C4.16016 22.41 3.82016 22.75 3.41016 22.75C3.00016 22.75 2.66016 22.41 2.66016 22C2.66016 17.73 6.85015 14.25 12.0002 14.25C17.1502 14.25 21.3401 17.73 21.3401 22C21.3401 22.41 21.0001 22.75 20.5901 22.75Z" fill="black"/>
              </svg>
            </a>
            <!-- <a href="<?php echo $_helper->getBaseLinkUrl(). 'wishlist' ?>" class="wishlist mr-1 mr-lg-2 pr-lg-1" title="Wishlist"><i class="porto-icon-wishlist-2"></i></a> -->
              <?php
              /** @var \Magento\Customer\Model\Session $customerSession */
              $customerSession = $block->getLayout()->createBlock(\Magento\Customer\Block\Account\AuthorizationLink::class)->isLoggedIn();
              ?>
              <div id="profile-popup" style="display: none;">
                  <div class="profile-popup-content">
                      <?php if ($customerSession): ?>
                        <a href="<?php echo $_helper->getBaseLinkUrl(). 'customer/account/' ?>" class="profile-link"><?php echo __('My Profile'); ?></a>
                        <hr>
                        <a href="<?php echo $block->getUrl('customer/account/logout'); ?>" class="logout-link"><?php echo __('Logout'); ?></a>
                      <?php else: ?>
                        <a href="<?php echo $block->getUrl('customer/account/login'); ?>" class="login-link"><?php echo __('Log In'); ?></a>
                      <?php endif; ?>
                  </div>
              </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <?php echo $this->getChildHtml("navigation.sections"); ?>
<?php else: ?>
  <div class="main-panel-top">
      <div class="container">
          <div class="main-panel-inner">
              <div class="panel wrapper">
                <div class="header-left">
                  <div class="panel header">
                      <?php echo $this->getChildHtml("currency"); ?>
                      <?php echo $this->getChildHtml("store_language"); ?>
                  </div>
                </div>
                <div class="header-right">
                  <div class="panel header show-icon-tablet">
                    <div class="top-links-icon">
                      <a href="javascript:;"><?php echo __('Links');?></a>
                    </div>
                    <?php echo $this->getChildHtml("header.links"); ?>
                  </div>
                  <?php echo $this->getChildHtml("custom_block_top"); ?>
                </div>
              </div>
          </div>
      </div>
  </div>
  <div class="header-main">
    <div class="header content header-row">
      <div class="header-left">
        <span data-action="toggle-nav" class="action nav-toggle"><span><?php echo __('Toggle Nav') ?></span></span>
        <?php echo $this->getChildHtml("logo"); ?>
      </div>
      <div class="header-center">
        <div class="search-area show-icon-tablet">
          <a href="javascript:void(0);" class="search-toggle-icon"><span><i class="porto-icon-magnifier"></i></span></a>
          <?php echo $this->getChildHtml("top.search"); ?>
        </div>
      </div>
      <div class="header-right">
      <?php echo $this->getChildHtml("minicart"); ?>
        <div class="header-contact">
          <?php echo $this->getChildHtml("custom_block"); ?>
          <a href="<?php echo $_helper->getBaseLinkUrl(). 'customer/account/' ?>" class="my-account m-l-xs mr-1 mr-lg-2" title="My Account"><i class="porto-icon-user-2"></i></a>
          <a href="<?php echo $_helper->getBaseLinkUrl(). 'wishlist' ?>" class="wishlist mr-1 mr-lg-2 pr-lg-1" title="Wishlist"><i class="porto-icon-wishlist-2"></i></a>
        </div>
      </div>
    </div>
  </div>
<?php endif; ?>
</header>
<?php if($header_type == 10): ?>
</div>
<?php endif; ?>
<?php
    if ($show_notice && $show_notice == 2)
        echo $this->getChildHtml("porto_custom_notice");
?>


<script type="text/javascript">
  require([
        'jquery'
    ], function ($) {
    $(document).ready(function($) {
        $('[data-action="close-nav"]').on('click', function() {
            $('html').removeClass('nav-open');
        });

        $('[data-action="close-nav"]').on('click', function() {
            $('html').removeClass('nav-open');
        });

    // Open profile popup
    $('.my-account').on('click', function(event) {
        event.preventDefault();
        var $popup = $('#profile-popup');
        if ($popup.is(':visible')) {
            $popup.hide();
        } else {
            $popup.show();
        }
    });

    // Close profile popup when clicking outside
    $(document).mouseup(function(e) {
        var $popup = $('#profile-popup');
        if (!$popup.is(e.target) && $popup.has(e.target).length === 0) {
            $popup.hide();
        }
    });
    });
  });
</script>