<?php

$id  = $this->getRequest()->getParam('id');

$categoryAttributeValue = $block->getChooseCategoryQuizValue($id);

$data = $block->getCategoryStatus($id);

$status = isset($data['status']) ? $data['status'] : null;
$getoldquestionurl = $block->getUrl('productrecommendationquiz/jump/getoldquestion');
$getquestion = $block->getUrl('productrecommendationquiz/jump/getquestion');
$resetvalue = $block->getUrl('productrecommendationquiz/jump/resetvalue');
$getnextquestion = $block->getUrl('productrecommendationquiz/jump/getnextquestion');
$getbackquestion = $block->getUrl('productrecommendationquiz/jump/getbackquestion');

?>
<?php

if ((int) $status !== 0) {
    $questionData = $block->getQuestionData($categoryAttributeValue);
    if (!empty($questionData) && $questionData !== "null") {
?>
        <div class="flex py-lg-5 py-3 quiz-block">
            <form action="#">
                <div id="quiz-container">
                    <div class="question" data-question-id="">
                        <p></p>
                    </div>
                    <div class="options">
                    </div>
                    <div class="customer_button">
                        <button type="button" id="back-question" class="btn secondary-btn">Back</button>
                        <button type="button" id="reset-question" class="btn">Reset</button>
                        <button type="button" id="next-question" class="btn primary-btn">Next</button>
                    </div>
                </div>
            </form>
        </div>
<?php
    }
} else {
}
?>
<script type="text/javascript">
    var categoryAttributeValue = <?php echo json_encode($categoryAttributeValue); ?>;
    var categoryId = <?php echo json_encode($id); ?>;
    var getOldQuestionUrl = <?php echo json_encode($getoldquestionurl); ?>;
    var getquestion = <?php echo json_encode($getquestion); ?>;
    var resetvalue = <?php echo json_encode($resetvalue); ?>;
    var getnextquestion = <?php echo json_encode($getnextquestion); ?>;
    var getbackquestion = <?php echo json_encode($getbackquestion); ?>;

    require(['questionScript'], function(questionScript) {
    });

</script>