<?php
/**
 * Webkul Software.
 *
 * @category   Webkul
 * @package    Webkul_Recurring
 * @author     Webkul Software Private Limited
 * @copyright  Webkul Software Private Limited (https://webkul.com)
 * @license    https://store.webkul.com/license.html
 */
    $model = $block->getSubscriptions();
    $order = $block->getOrder();
?>
<div class="subscriptions-information">
    <table class="admin__table-secondary">
        <tbody>
        <?= $block->getChildHtml() ?>
        <tr>
            <th><?= $escaper->escapeHtml(__('Subscription Type :')) ?></th>
            <td>            
                <?= $escaper->escapeHtml($block->getRecurringProductPlans()) ?>
            </td>
        </tr>
        <tr>
            <th><?= $escaper->escapeHtml(__('Start Date :')) ?></th>
            <td>         
                <?= $escaper->escapeHtml($block->getStartDate()) ?>
            </td>
        </tr>
        <tr>
            <th><?= $escaper->escapeHtml(__('Initial Order Id :')) ?></th>
            <td>
                <a href="<?= $escaper->escapeUrl($block->getOrderUrl()) ?>" target="_blank" >
                <?= $escaper->escapeHtml($block->getOrderId()) ?>
                </a>
            </td>
        </tr>
        <?php
            $product  = $block->getProduct();
            $customer = $block->getCustomer();
        ?>
        <tr>
            <th><?= $escaper->escapeHtml(__('Product Name :')) ?></th>
            <td>
            <?php if ($product->getId()): ?>
                <a href="<?= $escaper->escapeUrl($product->getProductUrl()) ?>" target="_blank" >
                <?= $escaper->escapeHtml($product->getName()) ?>
                </a>
            <?php else: ?>
                <?= $escaper->escapeHtml($model->getProductName()) ?>
            <?php endif; ?>
            </td>
        </tr>
        <tr>
            <th><?= $escaper->escapeHtml(__('Customer Name :')) ?></th>
            <td>
            <?php if ($customer->getId()): ?>
                <a href="<?= $escaper->escapeUrl($block->getCustomerUrl($customer->getId())) ?>" target="_blank" >
                <?= $escaper->escapeHtml($customer->getFirstname()." ".$customer->getLastname()) ?>
                </a>
            <?php else: ?>
                <?= $escaper->escapeHtml($model->getCustomerName()) ?>
            <?php endif; ?>
            </td>
        </tr>
        <tr>
            <th><?= $escaper->escapeHtml(__('Created At :')) ?></th>
            <td>         
                <?= $escaper->escapeHtml($block->getCreateDate()) ?>
            </td>
        </tr>
        <tr>
            <th><?= $escaper->escapeHtml(__('Status :')) ?></th>
            <td>         
                <?= $escaper->escapeHtml($block->getStatus($model->getStatus())) ?>
            </td>
        </tr>
        <?php if ($model->getRefProfileId()): ?>
        <tr>
            <th><?= $escaper->escapeHtml(__('Reference Transaction Id :')) ?></th>
            <td>         
                <?= $escaper->escapeHtml($model->getRefProfileId()) ?>
            </td>
        </tr>
        <?php endif; ?>
        </tbody>
    </table>
</div>
<div class="payment-information">
<label class="wk_label"><?= $escaper->escapeHtml(__('Payment and Shipping information'))?></label>
<hr>
    <div class="wk_table">
        <table class="admin__table-secondary">
            <tbody>
            <?= $block->getChildHtml() ?>
            <tr>
                <th><?= $escaper->escapeHtml(__('Initial Fee :')) ?></th>
                <td>            
                    <?= /* @noEscape */ $block->getFormattedPrice($block->getRecurringProductPlanInitialFee()) ?>
                </td>
            </tr>
            <tr>
                <th><?= $escaper->escapeHtml(__('Subscription Charge :')) ?></th>
                <td>         
                    <?= /* @noEscape */ $block->getSubscriptionCharge() ?>
                </td>
            </tr>
            <tr>
                <th><?= $escaper->escapeHtml(__('Last Billing Date :')) ?></th>
                <td>                
                <?= $escaper->escapeHtml($block->getStartDate()) ?>
                    </a>
                </td>
            </tr>
            <?php
                $product  = $block->getProduct();
                $customer = $block->getCustomer();
            ?>
            <tr>
                <th><?= $escaper->escapeHtml(__('Next Billing Date :')) ?></th>
                <td>
                    <?= $escaper->escapeHtml($block->getValidTill()) ?>
                </td>
            </tr>
            <tr>
                <th><?= $escaper->escapeHtml(__('Amount to be Billed :')) ?></th>
                <td>
                <?= /* @noEscape */ $block->getSubscriptionCharge()?>
                </td>
            </tr>
            <tr>
                <th><?= $escaper->escapeHtml(__('Payment Method :')) ?></th>
                <td>         
                    <?= $escaper->escapeHtml($order->getPayment()->getMethodInstance()->getTitle()); ?>
                </td>
            </tr>
            <tr>
                <th><?= $escaper->escapeHtml(__('Billing Address :')) ?></th>
                <td>         
                
                <?= /* @noEscape */ $block->getFormattedAddress($order->getBillingAddress())?>
                </td>
            </tr>
            <?php if ($model->getRefProfileId() && !$order->getIsVirtual()): ?>
            <tr>
                <th><?= $escaper->escapeHtml(__('Shipping Address :')) ?></th>
                <td>         
                <?= /* @noEscape */ $block->getFormattedAddress($order->getShippingAddress())?>
                </td>
            </tr>
            <?php endif; ?>
            </tbody>
        </table>
    </div>
</div>

<?php if ($model->getCancellationReason()): ?>
    <div class="payment-information">
    <label class="wk_label"><?=$escaper->escapeHtml(__('Reason of Cancellation'))?></label>
    <hr>
    <label><?=  $escaper->escapeHtml($model->getCancellationReason());?></label>  
    </div>
<?php endif; ?>